### ISSUE TITLE
Deprecated selector in `pulsing-cursor/styles/pulsing-cursor.atom-text-editor.less`

### ISSUE THREAD

**Issue by harrison-drift** [dmnd/pulsing-cursor#4]
In `pulsing-cursor/styles/pulsing-cursor.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host(.is-focused) .cursors > .cursor` => `atom-text-editor .cursors > .cursor`

* `:host(.is-focused) .cursors.blink-off > .cursor` => `atom-text-editor .cursors.blink-off > .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by howkj1** [comment]
Confirmed... same warning in my editor. (v1.13.0)

![screen shot 2017-01-17 at 11 24 51 pm](https://cloud.githubusercontent.com/assets/9202867/22051937/5c314d44-dd0c-11e6-8360-94d003ea9fcc.png)

**Comment by JAT1M** [comment]
In the Deprecated selectors window,
click on `pulsing-cursor/styles/pulsing-cursor.atom-text-editor.less`

or go to the file itself, its located here:
Linux & Mac OS X
`~/.atom/packages/pulsing-cursor/styles/pulsing-cursor.atom-text-editor.less`

Windows
`%userprofile%\.atom\packages\pulsing-cursor\styles\pulsing-cursor.atom-text-editor.less`

in that file, replace `:host(.is-focused)` with `atom-text-editor`
and restart Atom

tested & confirmed @ Atom 1.14.1
